### ISSUE TITLE
Define the standard attributecode spreadsheet requirements and conventions for input

### ISSUE THREAD

**Issue by DennisClark** [nexB/attributecode#1]
Define the standard spreadsheet requirements and conventions for an input file for attributecode.

**Comment by chinyeungli** [comment]
This following are the standard fields that we currently have
```
        self.fields = OrderedDict([
            ('name', Field()),
            ('version', Field()),

            ('download_url', Field()),
            ('homepage_url', Field()),
            ('package_url', Field()),
            ('notes', Field()),

            ('license_expression', Field()),
            ('license_key', Field()),
            ('license_name', Field()),
            ('license_file', Field()),
            ('license_url', Field()),
            ('copyright', Field()),
            ('notice_file', Field()),
        ])
```

We don't have any field validation functions (as to make the code simpler) and there is no restriction of having custom fields (except the field name cannot contain illegal characters: `is_valid_name = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$').match`)

In another word, there is no restriction and/or requirement to use the tool except the field name cannot contains special characters.

Comments/Feedbacks are welcome is the current approach good, or we should be more restrict to have define certain requirement/restriction.

**Comment by chinyeungli** [comment]
See the https://nexb-attributecode.readthedocs-hosted.com/en/latest/general.html#input-requirement for details

**Comment by chinyeungli** [comment]
I think we can close this as we already have the RTD for the input-requirement (See above) and some sample inputs to look at: https://github.com/nexB/attributecode/tree/main/samples
